### ISSUE TITLE
Problems on train lightcnn?

### ISSUE THREAD

**Issue by BrettLL** [BradyFU/DVG#10]
when you train lightcnn, you use the mmd loss which not matches paper (verification loss), is mmd loss better?

**Comment by BradyFU** [comment]
What does ‘verification loss’ mean?

**Comment by BrettLL** [comment]
sorry, 'verfication loss' means the pair distance loss in paper eq(12).

**Comment by BradyFU** [comment]
You can choose to use the MMD loss or the pair distance loss. There is no significant difference, because both of them are used to reduce the domain gap.
