### ISSUE TITLE
About CASIA NIR-VIS 2.0

### ISSUE THREAD

**Issue by Comedian1926** [BradyFU/DVG#11]
Thank you very much for your work. I am currently applying for the CASIA NIR-VIS 2.0 data set. What is the general application period? Or is there any other data set recommendation.thk

**Comment by BradyFU** [comment]
Thank you for your interest in our work. You can try to get the links of some datasets from here: [https://github.com/ZhaoJ9014/face.evoLVe.PyTorch#Data-Zoo](url)
