### ISSUE TITLE
Regarding the redistribution of CASIA NIR-VIS 2.0

### ISSUE THREAD

**Issue by miiya369** [BradyFU/DVG#13]
Hi, thank you for sharing your interesting work.
I want to reproduct your results, however I have a problem regarding the data.
The CASIA NIR-VIS 2.0 is now not available in their project page so that I've contacted some member of CASIA but there no responses.

Then I found the data in following page:
https://github.com/ZhaoJ9014/face.evoLVe.PyTorch#Data-Zoo
but I wonder that redistribution of the dataset allowed or not, because the RELEASE AGREEMENT of the dataset says:
> Redistribution: Without prior approval from Prof. Stan Z. Li, the creator of the database, the CASIA NIR-VIS 2.0 Database, either entirely or partly, should not be further distributed, published, copied, or disseminated in any way or form, no matter for profitable use or not, including further distribution to a different department or organization in the same system.
> (c.f. http://www.cbsr.ia.ac.cn/english/HFB_Agreement/NIR-VIS-2.0_agreements.pdf)

Do you know can we use the database without the approval?

Thank you.

**Comment by BradyFU** [comment]
Thanks for your interest in our work. I'm not sure about the redistribution of CASIA NIR-VIS 2.0.

**Comment by miiya369** [comment]
Thank you for your quick reply.

I have an another question about training/testing protocol for the Oulu-CASIA NIR-VIS database.
You only use 40 persons in 80 total for training/testing. (10 persons who be taken in Oulu Univ, and 30 persons who be taken in CASIA).
But the specific information (i.e. which persons are actually used) is not shown in your paper.
I have searched previous work but I cannot found that.
Could you inform me the training/testing protocol in detail?

**Comment by BradyFU** [comment]
You can leave me an email address and I will send you the protocol files.

**Comment by miiya369** [comment]
Thank you for your kind support.
I will send email to your email address.
