### ISSUE TITLE
Dataset setting questions

### ISSUE THREAD

**Issue by leoliu37** [BradyFU/DVG#2]
Thanks for your sharing. I want to reproduce your work and meet some problems.
In the script, how to set ‘train_list’ and ‘img_root ’？ Would you provide more details about the work?

**Comment by AlfredXiangWu** [comment]
The "img_root" is the root path of your own dataset. 

The "train_list" is a path to your image list file with labels. The simple example of the format are as follows:

> NIR/s2_NIR_10166_013.jpg 351 0
> VIS/s2_VIS_10166_002.jpg 351 1
> NIR/s1_NIR_00009_003.jpg 8 0
> VIS/s1_VIS_00009_009.jpg 8 1

where the first column is the name of image, the second one is the identity label and the third is the domain label, resepctively.

**Comment by Herb996** [comment]
后面两个标签，，如何生成的啊，，，不是很懂，，，
