### ISSUE TITLE
which dataset be used when runing "run_train_generator.sh"?

### ISSUE THREAD

**Issue by xieshenru** [BradyFU/DVG#8]
Can you give some instructions for using“train_generator.py”?What kind of data is used? NIR or RGB？

**Comment by BradyFU** [comment]
The training dataset is CASIA NIR-VIS 2.0, including both NIR and VIS images. We use paired NIR-VIS images to train our generator.

**Comment by BradyFU** [comment]
Refer to _run_train_generator.sh_, **img_root** is the path of your dataset, and **train_list** is the path of your image list. The example of the image list is
> NIR/s2_NIR_10166_013.jpg 351 0
VIS/s2_VIS_10166_002.jpg 351 1
NIR/s1_NIR_00009_003.jpg 8 0
VIS/s1_VIS_00009_009.jpg 8 1

From left to right, each column is the image name, the identity label, and the domain label, resepctively.
