### ISSUE TITLE
A model problem

### ISSUE THREAD

**Issue by xtp798325962** [BradyFU/DVG#9]
Hello, according to the link you gave, I downloaded the lightcnn pre training model, but when I used it, the following errors occurred.would you give me an answer? is the model download process wrong or other reasons?
### ~start
train generator
Traceback (most recent call last):
  File "train_generator.py", line 187, in <module>
Namespace(all_epochs=50, batch_size=8, gpu_ids='0', hdim=128, img_root='./data_set/NIR-VIS/picture/', ip_model='LightCNN_29Layers_V2_checkpoint.pth.tar', lambda_ip=1000.0, lambda_mmd=50.0, lambda_pair=5.0, lr=0.0002, out_path='results/', pre_epoch=0, print_freq=20, save_epoch=10, test_epoch=10, train_list='./data_set/NIR-VIS/casia_train.txt', workers=8)
=> loading pretrained identity preserving model 'LightCNN_29Layers_V2_checkpoint.pth.tar'
    main()
  File "train_generator.py", line 65, in main
    checkpoint = torch.load(args.ip_model)
  File "/home/xiatianpeng/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/xiatianpeng/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/torch/serialization.py", line 620, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 4612705732743817355 got 384

**Comment by BradyFU** [comment]
It may be caused by the PyTorch version. Our model is trained on Pytorch 0.4.1 && Torchvision 0.2.1.

**Comment by xtp798325962** [comment]
Thank you for your reply. In this case, let me have a try to train a lightcnn model myself.

**Comment by BradyFU** [comment]
You're welcome.
